name: Publish Docker Image

on:
  # push:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * 0"

env:
  IMAGE_NAME: fkodom/deeplearning

jobs:
  docker:
    runs-on: ubuntu-latest

    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        ubuntu: ["20.04"]
        cuda: ["11.4.2"]
        python: ["3.9"]
        torch: ["1.9", "1.10"]
        dev: [false, true]

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          DOCKERFILE: docker/deeplearning/pytorch/Dockerfile
          TAG_FORMAT: py${{ matrix.python }}-torch${{ matrix.torch }}-cuda${{ matrix.cuda }}
        with:
          file: ${{ matrix.dev && env.DOCKERFILE || format('{0}.{1}', env.DOCKERFILE, 'dev') }}
          tags: ${{ env.IMAGE_NAME }}:${{ matrix.dev && env.TAG_FORMAT || format('{0}-{1}', env.TAG_FORMAT, 'dev') }}
          push: true
          no-cache: true
