name: Docker - Deep Learning, PyTorch

on:
  workflow_dispatch:
  schedule:
    # Run every Sunday at midnight Central time (5:00 UTC)
    # NOTE: * is a special character in YAML so use quotes.
    - cron: "0 5 * * 0"

env:
  IMAGE_NAME: fkodom/deeplearning

jobs:
  docker:
    runs-on: ubuntu-latest

    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        ubuntu: ["20.04"]
        cuda: ["11.4.2"]
        python: ["3.9", "3.10"]
        torch: ["1.9", "1.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Set current date string
        run: echo "DATE=$(date '+%Y%m%d')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: docker/deeplearning/pytorch/Dockerfile
          tags: | 
            ${{ env.IMAGE_NAME }}:py${{ matrix.python }}-torch${{ matrix.torch }}-cuda${{ matrix.cuda }}
            ${{ env.IMAGE_NAME }}:py${{ matrix.python }}-torch${{ matrix.torch }}-cuda${{ matrix.cuda }}-${{ env.DATE }}
          push: true
          no-cache: true
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu }}
            CUDA_VERSION=${{ matrix.cuda }}
            PY_VERISON=${{ matrix.python }}
            TORCH_VERSION=${{ matrix.torch }}
