name: Docker - Deep Learning, Flax

on:
  workflow_dispatch:
  schedule:
    # Run every Sunday at midnight Central time (5:00 UTC)
    # NOTE: * is a special character in YAML so use quotes.
    - cron: "0 5 * * 0"

env:
  IMAGE_NAME: fkodom/deeplearning

jobs:
  docker-cuda:
    runs-on: ubuntu-latest

    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        ubuntu: ["20.04"]
        cuda: ["11.1.1"]
        python: ["3.9", "3.10"]
        jax: ["0.3"]
        flax: ["0.5"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: docker/deeplearning/pytorch/cuda.Dockerfile
          tags: |
            ${{ env.IMAGE_NAME }}:py${{ matrix.python }}-jax${{ matrix.jax }}-flax${{ matrix.flax }}-cuda${{ matrix.cuda }}
          push: true
          no-cache: true
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu }}
            CUDA_VERSION=${{ matrix.cuda }}
            PY_VERISON=${{ matrix.python }}
            JAX_VERSION=${{ matrix.jax }}
            FLAX_VERSION=${{ matrix.flax }}

  docker-cpu:
    runs-on: ubuntu-latest

    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9", "3.10"]
        jax: ["0.3"]
        flax: ["0.5"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: docker/deeplearning/pytorch/cpu.Dockerfile
          tags: |
            ${{ env.IMAGE_NAME }}:py${{ matrix.python }}-jax${{ matrix.jax }}-flax${{ matrix.flax }}-cpu
          push: true
          no-cache: true
          build-args: |
            PY_VERISON=${{ matrix.python }}
            JAX_VERSION=${{ matrix.jax }}
            FLAX_VERSION=${{ matrix.flax }}
